name: Order Repository CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: write

jobs:
  order-test:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16

        env:
          POSTGRES_DB: testdb
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres

        ports:
          - 5432:5432

        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 22

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Make Gradle Wrapper Executable
        run: chmod +x gradlew

      - name: Run Order Test

        run: ./gradlew integrationTest --no-configuration-cache
        env:
          JAVA_TOOL_OPTIONS: >
            -Ddb.url=jdbc:postgresql://localhost:5432/testdb
            -Ddb.user=postgres
            -Ddb.password=postgres


      - name: Copy Allure Environment
        if: always()
        run: |
          mkdir -p build/allure-results
          cp src/test/resources/environment.properties \
             build/allure-results/environment.properties

      - name: Checkout gh-pages branch
        if: always()
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages

      - name: Generate Allure Report
        if: always()
        uses: simple-elf/allure-report-action@master
        with:
          allure_results: Gradle_Project/build/allure-results
          allure_report: allure-report
          gh_pages: gh-pages
          allure_history: allure-history

      - name: Deploy report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history